### PR TITLE
Goertzelfix

### PR DESCRIPTION
**Pull request by dnrhead**
According to wikipedia and the paper of P. Sysel and P. Rajmic the last q1 and q2 should be changed.
`e^(j*2*pi*k/N)*q1 - q2 = q1*cos(*2*pi*k/N) + j*q1*sin(*2*pi*k/N) - q2`

### CODE REVIEW

**Comment by Harvie** [comment]
How is the program behaviour changed by this change? IIRC the original algorithm was also based on wikipedia pseudocode example some time ago... Is there something wrong with it? It seemed to be working just fine for me... (Just trying to understand reason for this PR)

**Comment by dnrhead** [comment]
You are caluculating the magnitude, so this inaccuracy chancels out, because sin^2+cos^2 = 1. 
I was just experimenting with the complex values, and these seemed to differ from other impementations I tried.
If you just need the magnitude, it would be enough to calculate the coeff (and not sine).

**Comment by Harvie** [comment]
Do i get it right, that your code is more suitable if you need to also get phase of the detected sine? While mine will only give you the amplitude? That sounds interresting. How do i get the phase angle out of it?

**Comment by dnrhead** [comment]
yeah, thats correct. For the magnitude the error chancels out, but the complex value is not correct.
Phase is atan(imag/real).
I just wrote a small matlab script to show the difference [https://github.com/dnrhead/goertzel_matlab](here). 
I added a view impementations (not just yours and mine), because the magnitude is scaled different in each impementation.
I pretty sure your scale factor of N/2 should be correct for sinusoidal signals. (in the example the amplitude is 1, so it seems right).

**Comment by Harvie** [comment]
Very cool. Thank you for your insight :)

**Pull request merged**
